"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {cuePoints,difficultyLimits,foreignPools,labels,mongolianFeatured,mongolianPools,type Difficulty,type Genre,type Mode} from "@/data/catalog";
type Track={trackId:number;artistId:number;trackName:string;artistName:string;previewUrl:string;artworkUrl100?:string;releaseDate?:string;wrapperType:string};
const genres:Genre[]=["all","new","hiphop","pop","rock","traditional"];
const norm=(s:string)=>(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zа-яөүё0-9]/gi,"");
const shuffle=<T,>(x:T[])=>{const a=[...x];for(let i=a.length-1;i>0;i--){const n=new Uint32Array(1);crypto.getRandomValues(n);const j=n[0]%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
export default function SongGame(){
 const [mode,setMode]=useState<Mode>("mongolian"),[genre,setGenre]=useState<Genre>("all"),[difficulty,setDifficulty]=useState<Difficulty>("medium"),[tracks,setTracks]=useState<Track[]>([]),[current,setCurrent]=useState<Track|null>(null),[level,setLevel]=useState(0),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[round,setRound]=useState(1),[loading,setLoading]=useState(true),[playing,setPlaying]=useState(false),[message,setMessage]=useState(""),[kind,setKind]=useState<""|"good"|"bad">(""),[guess,setGuess]=useState(""),[selected,setSelected]=useState<number|null>(null),[revealed,setRevealed]=useState(false),[volume,setVolume]=useState(.75);
 const audio=useRef<HTMLAudioElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),remaining=useRef(0),started=useRef(0),paused=useRef(false),limits=difficultyLimits[difficulty];
 const suggestions=useMemo(()=>{const q=norm(guess);return q?[...tracks,...(current?[current]:[])].filter((t,i,a)=>(norm(t.trackName).includes(q)||norm(t.artistName).includes(q))&&a.findIndex(x=>x.trackId===t.trackId)===i).slice(0,7):[]},[guess,tracks,current]);
 const finish=useCallback(()=>{if(timer.current)clearTimeout(timer.current);remaining.current=0;paused.current=false;audio.current?.pause();setPlaying(false)},[]);
 const takeNext=useCallback((list:Track[])=>{const [item,...rest]=list;if(!item)return false;if(timer.current)clearTimeout(timer.current);audio.current?.pause();try{const old:number[]=JSON.parse(localStorage.getItem("duuTaayaRecent")||"[]");localStorage.setItem("duuTaayaRecent",JSON.stringify([item.trackId,...old.filter(x=>x!==item.trackId)].slice(0,40)))}catch{}setCurrent(item);setTracks(rest);setLevel(0);setGuess("");setSelected(null);setRevealed(false);setMessage("");setKind("");remaining.current=0;paused.current=false;return true},[]);
 const load=useCallback(async()=>{setLoading(true);setMessage("Дууны санг бэлдэж байна…");setKind("");const pools=mode==="mongolian"?mongolianPools:foreignPools,featured=mode==="mongolian"?mongolianFeatured:{hiphop:[],pop:[],rock:[]};const ids=genre==="all"||genre==="new"?[...new Set(Object.values(pools).flat())]:(pools as Record<string,number[]>)[genre]||[],featuredIds=genre==="all"||genre==="new"?[...new Set(Object.values(featured).flat())]:(featured as Record<string,number[]>)[genre]||[],artists=new Set(ids),songs=new Set(featuredIds),country=mode==="foreign"?"us":"au";try{const calls=ids.map(id=>fetch(`https://itunes.apple.com/lookup?id=${id}&entity=song&limit=100&country=${country}`).then(r=>r.json()).catch(()=>({results:[]})));if(featuredIds.length)calls.push(fetch(`https://itunes.apple.com/lookup?id=${featuredIds.join(",")}&entity=song&country=${country}`).then(r=>r.json()).catch(()=>({results:[]})));const data=await Promise.all(calls);let list:Track[]=data.flatMap(x=>x.results||[]).filter((x:Track)=>x.wrapperType==="track"&&x.previewUrl&&x.trackName&&x.artistName&&(artists.has(Number(x.artistId))||songs.has(Number(x.trackId))));list=[...new Map(list.map(x=>[x.trackId,x])).values()];if(genre==="new")list=list.filter(x=>x.releaseDate&&new Date(x.releaseDate)>=new Date("2025-01-01"));list=shuffle(list);let recent=new Set<number>();try{recent=new Set(JSON.parse(localStorage.getItem("duuTaayaRecent")||"[]"))}catch{}list.sort((a,b)=>Number(recent.has(a.trackId))-Number(recent.has(b.trackId)));if(!takeNext(list))throw Error()}catch{setMessage("Дуу ачаалж чадсангүй. Интернэтээ шалгаад дахин оролдоорой.");setKind("bad")}finally{setLoading(false)}},[mode,genre,takeNext]);
 useEffect(()=>{const id=setTimeout(()=>void load(),0);return()=>clearTimeout(id)},[load]);useEffect(()=>{if(audio.current)audio.current.volume=volume},[volume]);
 const play=(restart=false,requestedLevel=level)=>{const a=audio.current;if(!a||!current)return;if(!restart&&playing){remaining.current=Math.max(0,remaining.current-(performance.now()-started.current));paused.current=true;if(timer.current)clearTimeout(timer.current);a.pause();setPlaying(false);return}if(restart){if(timer.current)clearTimeout(timer.current);a.pause();paused.current=false;remaining.current=0}if(!paused.current||remaining.current<=0){a.currentTime=cuePoints[current.trackId]??2.5;remaining.current=limits[requestedLevel]*1000}a.play().then(()=>{started.current=performance.now();paused.current=false;setPlaying(true);timer.current=setTimeout(finish,remaining.current)}).catch(()=>{setMessage("Аудио тоглож чадсангүй. Дахин дарна уу.");setKind("bad")})};
 const reveal=(ok:boolean)=>{setRevealed(true);setMessage(ok?"Зөв таалаа!":"Хариулт нь энэ байлаа.");setKind(ok?"good":"bad");setTimeout(()=>{setRound(r=>r>=10?1:r+1);if(!takeNext(tracks))load()},2600)};
 const submit=()=>{if(!current)return;const q=norm(guess);if(q.length<2){setMessage("Хариултаа эхлээд бичээрэй.");setKind("bad");return}const ok=selected?selected===current.trackId:norm(current.trackName).includes(q)||q.includes(norm(current.trackName));if(ok){setScore(s=>s+Math.max(20,100-level*20));setStreak(s=>s+1);reveal(true)}else{setStreak(0);setMessage("Арай биш байна — дахин оролдоорой.");setKind("bad")}};
 return <main className="shell"><aside className="side left"><div className="brand"><span className="mark">♫</span> Дуугаа Таа</div><p className="side-title">ХҮНДРЭЛ</p><div className="difficulty">{(["easy","medium","hard","expert"] as Difficulty[]).map(d=><button key={d} className={`diff ${difficulty===d?"active":""}`} onClick={()=>{setDifficulty(d);setLevel(0);setMessage(`${d[0].toUpperCase()+d.slice(1)} түвшин сонгогдлоо.`)}}>{d[0].toUpperCase()+d.slice(1)}</button>)}</div><button className="side-action" onClick={()=>{setScore(0);setStreak(0);setRound(1);load()}}>↻ &nbsp; Бүгдийг шинээр эхлэх</button></aside>
 <section className="center"><header className="top"><div className="score"><span><b>{score}</b>оноо</span><span><b>{streak}</b>дараалал</span></div></header><div className="mode-switch">{(["mongolian","foreign"] as Mode[]).map(m=><button key={m} className={`mode ${mode===m?"active":""}`} onClick={()=>{setMode(m);if(m==="foreign"&&genre==="traditional")setGenre("all");setScore(0);setStreak(0);setRound(1)}}>{m==="mongolian"?"🇲🇳 Монгол дуу":"🌍 Гадаад дуу"}</button>)}</div><nav className="genres">{genres.filter(g=>mode==="mongolian"||g!=="traditional").map(g=><button key={g} className={`chip ${genre===g?"active":""}`} onClick={()=>{setGenre(g);setRound(1)}}>{g==="all"?"Бүгд":g==="new"?"Шинэ":g==="traditional"?"Зохиолын":labels[g]}</button>)}</nav><section className="intro"><h1>{mode==="mongolian"?"Дуугаа ":"World hits "}<span>хэдхэн хормоос таа</span></h1><p>{mode==="mongolian"?"Баталгаажсан Монгол артистуудын сан":"Дэлхийн хит артистуудын сан"}</p></section>
 <section className="game"><div className="status"><span>{round} / 10</span><strong>{mode==="mongolian"?"МОНГОЛ":"ГАДААД"} · {labels[genre]}</strong></div><div className={`wave ${playing?"playing":""}`}>{Array.from({length:36},(_,i)=><i className="bar" key={i} style={{"--i":i,"--h":`${18+((i*37)%76)}px`} as React.CSSProperties}/>)}</div><div className="playrow"><button className="play" disabled={loading} onClick={()=>play()}>{playing?"Ⅱ":"▶"}</button></div><div className="duration"><b>{limits[level]}</b> секунд сонсоно</div><div className="answer"><div className="searchbox">{!!suggestions.length&&<div className="suggestions">{suggestions.map(t=><button className="suggestion" key={t.trackId} onClick={()=>{setSelected(t.trackId);setGuess(t.trackName)}}><b>{t.trackName}</b><span>{t.artistName}</span></button>)}</div>}<input value={guess} onChange={e=>{setGuess(e.target.value);setSelected(null)}} onKeyDown={e=>e.key==="Enter"&&submit()} autoComplete="off" placeholder="Дууны нэр эсвэл дуучин…"/></div><button className="primary" onClick={submit}>Таах</button></div><div className="actions"><button className="ghost" onClick={()=>{if(level<limits.length-1){const nextLevel=level+1;setLevel(nextLevel);play(true,nextLevel)}else setMessage("Хамгийн урт хэсэг дээр байна.")}}>+ Илүү сонсох</button><button className="ghost" onClick={()=>{setStreak(0);finish();reveal(false)}}>Алгасах</button></div><div className="steps">{limits.map((_,i)=><i key={i} className={`step ${i<=level?"on":""}`}/>)}</div><p className={`message ${kind}`}>{message}</p>{revealed&&current&&<div className="reveal-overlay" role="dialog" aria-modal="true" aria-label="Дууны хариулт"><div className={`reveal ${kind}`}><small>{kind==="good"?"ЗӨВ ХАРИУЛТ":"ХАРИУЛТ НЬ"}</small>{current.artworkUrl100&&<img src={current.artworkUrl100.replace("100x100","300x300")} alt=""/>}<strong>{current.trackName}</strong><span>{current.artistName}</span><em>Дараагийн дуу руу шилжиж байна…</em></div></div>}</section><p className="foot">Preview болон дууны мэдээллийг Apple Music каталогоос авна.</p></section>
 <aside className="side right"><p className="side-title">ТОГЛУУЛАЛТ</p><div className="setting"><div className="setting-card">▷ &nbsp; Богино хэсгээс</div><div className="setting-card hot">♫ &nbsp; 30 сек preview</div></div><p className="side-title">САН</p><div className="setting"><p className="tiny">Монгол, гадаад дуу тусдаа баталгаажсан артистын сангаас ачаална.</p></div><p className="side-title">ДУУНЫ ЧАНГА</p><div className="setting"><input className="volume" type="range" min="0" max="1" value={volume} step=".05" onChange={e=>setVolume(Number(e.target.value))}/></div></aside><audio ref={audio} src={current?.previewUrl} preload="auto" onEnded={finish}/></main>
}
